### PR TITLE
add author label in ExampleUnitTest.java

### PR DESCRIPTION
**Pull request by XuHuaiyu**
hi, hougr
I'm a crazy of you.
And I open a new pull request of your project.
Please merge it to the master branch.

### CODE REVIEW

**Comment by hougr** [comment]
Please change the author name to your name. Thanks!

**Comment by XuHuaiyu** [comment]
ok

**Comment by XuHuaiyu** [comment]
I have changed it.

**Comment by hougr** [comment]
Well done. Thanks!

**Pull request merged**
